name: Frontend CI Workflow

on:
  push:
    branches:
      - main
      - release
      - develop
      - feature/*
  delete:
    branches:
      - release
      - feature/*

jobs:
  call-npm-ci-cd-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/frontend-ci.yaml@main
