name: NPM CI/CD Workflow

on:
  push:
    branches:
      - main
      - release
      - develop
      - feature/*
  delete:
    branches:
      - release
      - feature/*

jobs:
  run-npm-ci:
    uses: netcracker/qubership-apihub-ci/.github/workflows/npm-ci.yaml@main
